import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/src/component/header";
import HeaderMobile from "@/src/component/header-mobile";
import SideNav from "@/src/component/side-nav";
import PageWrapper from "@/src/component/page-wrapper";
import MarginWidthWrapper from "@/src/component/margin-width-wrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white font-sans antialiased ${geistSans.variable} ${geistMono.variable}`}
      >
        <div className="flex">
          <main className="flex-1">
            <MarginWidthWrapper>
              <SideNav />
              <Header />
              <HeaderMobile />
              <PageWrapper>
                {children}
              </PageWrapper>
            </MarginWidthWrapper>
          </main>

        </div>

      </body>
    </html>
  );
}
